export const resourceKinds = [
  "epic",
  "label",
  "component",
  "release",
  "issue-type",
  "priority",
  "workflow",
  "custom-field",
  "template",
  "board",
  "milestone",
  "automation-rule",
  "notification-rule",
  "permission-scheme",
  "saved-filter",
];
